# Generated by Django 4.0.1 on 2022-01-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cr1000FtlaudMonitor',
            fields=[
                ('tmstamp', models.DateTimeField(db_column='TmStamp', primary_key=True, serialize=False)),
                ('recnum', models.BigIntegerField(db_column='RecNum')),
                ('measure_avg', models.FloatField(blank=True, db_column='measure_Avg', null=True)),
                ('ptemp', models.FloatField(blank=True, db_column='PTemp', null=True)),
            ],
            options={
                'db_table': 'CR1000_ftlaud_Monitor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='McleanMcleanmeasure',
            fields=[
                ('tmstamp', models.DateTimeField(db_column='TmStamp', primary_key=True, serialize=False)),
                ('recnum', models.BigIntegerField(db_column='RecNum')),
                ('temptilt_a', models.FloatField(blank=True, null=True)),
                ('temptilt_b', models.FloatField(blank=True, null=True)),
                ('tilt_a_deg', models.FloatField(blank=True, null=True)),
                ('tilt_b_deg', models.FloatField(blank=True, null=True)),
                ('laser1', models.FloatField(blank=True, null=True)),
                ('stringdisp', models.FloatField(blank=True, db_column='stringDisp', null=True)),
                ('sevolt', models.FloatField(blank=True, db_column='SEVolt', null=True)),
                ('tilt_temp', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Mclean_McleanMeasure',
                'managed': False,
            },
        ),
    ]
